### PR TITLE
Refactor shoot and intake commands

### PR DESCRIPTION
**Pull request by N1ckJay**

### CODE REVIEW

**Review by djb7c — APPROVED** [review]

**Review by N1ckJay — COMMENTED** [review]
This is the most efficent code I've ever seen. Great job Nicholas! Keep up the great work!

**Review by djb7c — APPROVED** [review]
Great job!

**Review by loganongithub — APPROVED** [review]
🫨

**Review by Rainylee00 — APPROVED** [review]
Great!

**Pull request merged**
